// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "SSEService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace  ::server;

class SSEServiceHandler : virtual public SSEServiceIf {
 public:
  SSEServiceHandler() {
    // Your initialization goes here
  }

  void add_entries(const std::string& label, const std::string& tag, const std::vector<std::string> & ciphertext_list) {
    // Your implementation goes here
    printf("add_entries\n");
  }

  void search(std::vector<int32_t> & _return, const std::string& token, const std::vector<SerialisedNode> & node_list, const int32_t level) {
    // Your implementation goes here
    printf("search\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::std::shared_ptr<SSEServiceHandler> handler(new SSEServiceHandler());
  ::std::shared_ptr<TProcessor> processor(new SSEServiceProcessor(handler));
  ::std::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::std::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::std::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

